import './globals.css'

import type { Metadata } from 'next'

import { MobileChecker, PreventZooming } from '@/app'

export const metadata: Metadata = {
  title: 'Next.js 15 with Firebase',
  description: 'Generated by create next app',
}

const L = ({ children }: Readonly<{ children: React.ReactNode }>) => (
  <html lang='ja'>
    <body>
      <PreventZooming />
      <MobileChecker>{children}</MobileChecker>
    </body>
  </html>
)

export default L
